# NumPy Assignment
Course: Python Programming
Topic: NumPy – Basics to Advanced

Run each code cell using the ▶ button in Google Colab.

## Question 1 – Student Marks Array

In [1]:
import numpy as np

marks = np.array([78, 65, 89, 56, 92])

print("Marks:", marks)
print("Number of dimensions:", marks.ndim)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data type:", marks.dtype)


Marks: [78 65 89 56 92]
Number of dimensions: 1
Shape: (5,)
Size: 5
Data type: int32


## Question 2 – Student Marks Access

In [2]:
import numpy as np

marks = np.array([72, 85, 64, 90, 76])

print("Marks:", marks)
print("First student's marks:", marks[0])
print("Third student's marks:", marks[2])
print("Last student's marks:", marks[-1])
print("First three students:", marks[0:3])
print("Second to fourth students:", marks[1:4])
print("Last two students:", marks[-2:])


Marks: [72 85 64 90 76]
First student's marks: 72
Third student's marks: 64
Last student's marks: 76
First three students: [72 85 64]
Second to fourth students: [85 64 90]
Last two students: [90 76]


## Question 3 – Subject-wise Marks

In [3]:
import numpy as np

marks = np.array([
    78, 85, 90,
    65, 72, 80,
    88, 91, 84,
    56, 62, 70,
    95, 89, 92
])

matrix = marks.reshape(5, 3)

print("Original Array:")
print(marks)
print("Reshaped Matrix:")
print(matrix)


Original Array:
[78 85 90 65 72 80 88 91 84 56 62 70 95 89 92]
Reshaped Matrix:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


## Question 4 – Internal and External Marks

In [4]:
import numpy as np

internal = np.array([20, 18, 22, 19, 21])
external = np.array([65, 70, 68, 72, 75])

final_marks = internal + external

print("Internal Marks:", internal)
print("External Marks:", external)
print("Final Marks:", final_marks)


Internal Marks: [20 18 22 19 21]
External Marks: [65 70 68 72 75]
Final Marks: [85 88 90 91 96]


## Question 5 – Pass Percentage Analysis

In [5]:
import numpy as np

marks = np.array([45, 78, 56, 32, 91])

passed = marks >= 50

print("Marks:", marks)
print("Students scoring 50 or above:", passed)
print("Qualified Marks:", marks[passed])


Marks: [45 78 56 32 91]
Students scoring 50 or above: [False  True  True False  True]
Qualified Marks: [78 56 91]


## Question 6 – Average Marks

In [6]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

average = np.mean(marks, axis=1)

print("Marks:")
print(marks)
print("Average marks of each student:")
print(average)


Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Average marks of each student:
[84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


## Question 7 – Class Performance Statistics

In [7]:
import numpy as np

marks = np.array([67, 82, 91, 74, 58])

print("Marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard Deviation:", np.std(marks))


Marks: [67 82 91 74 58]
Total: 372
Average: 74.4
Highest: 91
Lowest: 58
Standard Deviation: 11.46472851837321


## Question 8 – Subject-wise Performance

In [8]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

subject_total = np.sum(marks, axis=0)

print("Marks:")
print(marks)
print("Subject-wise Total:")
print(subject_total)


Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Subject-wise Total:
[382 399 416]


## Question 9 – Student-wise Performance

In [9]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

student_total = np.sum(marks, axis=1)

print("Marks:")
print(marks)
print("Student-wise Total:")
print(student_total)


Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Student-wise Total:
[253 217 263 188 276]


## Question 10 – Student Ranking

In [10]:
import numpy as np

marks = np.array([245, 278, 219, 290, 256])

sorted_indices = np.argsort(marks)[::-1]
sorted_marks = marks[sorted_indices]

print("Original Marks:", marks)
print("Marks in descending order:")
print(sorted_marks)
print("Ranking:")

for rank, index in enumerate(sorted_indices, start=1):
    print("Rank", rank, "- Student", index + 1, "- Marks:", marks[index])


Original Marks: [245 278 219 290 256]
Marks in descending order:
[290 278 256 245 219]
Ranking:
Rank 1 - Student 4 - Marks: 290
Rank 2 - Student 2 - Marks: 278
Rank 3 - Student 5 - Marks: 256
Rank 4 - Student 1 - Marks: 245
Rank 5 - Student 3 - Marks: 219


## Question 11 – Duplicate Marks Analysis

In [11]:
import numpy as np

marks = np.array([85, 92, 85, 76, 92])

unique_marks = np.unique(marks)

print("Original Marks:", marks)
print("Unique Marks:", unique_marks)


Original Marks: [85 92 85 76 92]
Unique Marks: [76 85 92]


## Question 12 – Missing Marks

In [12]:
import numpy as np

marks = np.array([78, 85, np.nan, 92, 67])

average = np.nanmean(marks)

print("Marks:", marks)
print("Average without missing value:", average)


Marks: [78. 85. nan 92. 67.]
Average without missing value: 80.5


## Question 13 – Grade Classification

In [13]:
import numpy as np

marks = np.array([95, 82, 74, 61, 45])

grades = np.select(
    [
        marks >= 90,
        marks >= 80,
        marks >= 70,
        marks >= 60
    ],
    [
        "A",
        "B",
        "C",
        "D"
    ],
    default="F"
)

print("Marks:", marks)
print("Grades:", grades)


Marks: [95 82 74 61 45]
Grades: ['A' 'B' 'C' 'D' 'F']


## Question 14 – Random Marks Generation

In [14]:
import numpy as np

np.random.seed(10)

marks = np.random.randint(0, 101, 5)

print("Randomly Generated Marks:")
print(marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard Deviation:", np.std(marks))


Randomly Generated Marks:
[  9 100  15  64  28]
Total: 216
Average: 43.2
Highest: 100
Lowest: 9
Standard Deviation: 34.219292803913994


## Question 15 – Student Performance Analysis

In [15]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
highest = np.max(marks, axis=1)
lowest = np.min(marks, axis=1)

class_average = np.mean(marks)
above_average = average > class_average

print("Student Marks:")
print(marks)
print("Total Marks:")
print(total)
print("Average Marks:")
print(average)
print("Highest Marks:")
print(highest)
print("Lowest Marks:")
print(lowest)
print("Class Average:", class_average)
print("Students above class average:")

for i in range(len(marks)):
    if above_average[i]:
        print("Student", i + 1, "- Average:", average[i])


Student Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Total Marks:
[253 217 263 188 276]
Average Marks:
[84.33333333 72.33333333 87.66666667 62.66666667 92.        ]
Highest Marks:
[90 80 91 70 95]
Lowest Marks:
[78 65 84 56 89]
Class Average: 79.8
Students above class average:
Student 1 - Average: 84.33333333333333
Student 3 - Average: 87.66666666666667
Student 5 - Average: 92.0
